apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: workshop
  name: woltsu-unity-kubernetes-workshop
  labels:
    app: woltsu-unity-kubernetes-workshop

spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: woltsu-unity-kubernetes-workshop

  template:
    metadata:
      labels:
        app: woltsu-unity-kubernetes-workshop
      annotations:
    spec:
      containers:
        - image: gcr.io/unity-ads-workshop-test/woltsu-unity-kubernetes-workshop:latest
          name: woltsu-unity-kubernetes-workshop
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 0.1
              memory: 128Mi
            limits:
              cpu: 0.5
              memory: 1024Mi
          env:
            - name: TEST
              value: Test env value

      nodeSelector:
        service: workshop