kind: Service
apiVersion: v1
metadata:
  labels:
    app: woltsu-unity-kubernetes-workshop
  name: woltsu-unity-kubernetes-workshop
  namespace: workshop

spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: woltsu-unity-kubernetes-workshop